version: "3.7"
services:
  traefik:
    image: traefik:v2.10
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.http.routers.traefik.rule=Host(`localhost`)"
      - "traefik.http.routers.traefik.service=api@internal"
    networks:
      - traefik_network
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]

  demo-java:
    image: ratife/igy-demo-java:0.1
    networks:
      - traefik_network
    labels:
      - "traefik.http.routers.java.rule=PathPrefix(`/api/java`)"
      - "traefik.http.routers.java.entrypoints=web"
      - "traefik.http.middlewares.java-stripprefix.stripprefix.prefixes=/api/java"
      - "traefik.http.routers.java.middlewares=java-stripprefix"
      - "traefik.http.services.java.loadbalancer.server.port=8080"
    deploy:
      replicas: 5
      placement:
        constraints: [node.role == worker]

  demo-php:
    image: ratife/igy-demo-php:0.1
    labels:
      - "traefik.http.routers.php.rule=PathPrefix(`/api/php`)"
      - "traefik.http.routers.php.entrypoints=web"
      - "traefik.http.middlewares.php-stripprefix.stripprefix.prefixes=/api/php"
      - "traefik.http.routers.php.middlewares=php-stripprefix"
      - "traefik.http.services.php.loadbalancer.server.port=80"
    networks:
      - traefik_network
    deploy:
      replicas: 5
      placement:
        constraints: [node.role == worker]

  demo-python:
    image: ratife/igy-demo-python:0.1
    labels:
      - "traefik.http.routers.python.rule=PathPrefix(`/api/python`)"
      - "traefik.http.routers.python.entrypoints=web"
      - "traefik.http.middlewares.python-stripprefix.stripprefix.prefixes=/api/python"
      - "traefik.http.routers.python.middlewares=python-stripprefix"
      - "traefik.http.services.python.loadbalancer.server.port=5000"
    networks:
      - traefik_network
    deploy:
      replicas: 5
      placement:
        constraints: [node.role == worker]

networks:
  traefik_network:
    driver: overlay
